---
configSite: PJ_girdle
config: 
    - year      : 2007
      fillTair  :
          - 
            siteType    : nmeg
            siteID      : 4    # PJ control
            linfit      : false
          - 
            siteType    : nmeg
            siteID      : 3    # Juniper Savanna
            linfit      : false
      fillrH    :
          - 
            siteType    : nmeg
            siteID      : 4    # PJ control
            linfit      : false
          - 
            siteType    : nmeg
            siteID      : 3    # Juniper Savanna
            linfit      : false
      fillRg    : 
          - 
            siteType    : nmeg
            siteID      : 4    # PJ control
            linfit      : false
          - 
            siteType    : nmeg
            siteID      : 3    # Juniper Savanna
            linfit      : false
      fillPrecip:
          - 
            siteType    : nmeg
            siteID      : 4    # PJ control
            linfit      : false
          - 
            siteType    : prism
            siteID      : PJ_girdle
            linfit      : false
...
