% Compare MCon soil data Marcy used in promotion talk with NMEG daily files
% made in export_daily_soilmet.py
load('MCon_SWC_compare.mat')
data = replace_badvals(data,[-9999],1e-10);

keep_idx = find(isfinite(data.shall_swc) & ...
                isfinite(data.mid_swc) & ...
                isfinite(data.deep_swc) & ...
                isfinite(data.AverageOfSWC_5cm) & ...
                isfinite(data.AverageOfSWC_20cm) & ...
                isfinite(data.AverageOfSWC_50cm)    );
            
data = data(keep_idx,:);

plot_bivariate_comparison(data.AverageOfSWC_5cm,data.shall_swc,...
    data.timestamp, ...
    'general',...  
    'varnames', {'Marcy', 'NMEG'}); 