function [fitresult, gof, output,xData, yData] = createFit(NMEGvar, EPvar)
%CREATEFIT(NMEGVAR,EPVAR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : NMEGvar
%      Y Output: EPvar
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jun-2016 12:03:27


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( NMEGvar, EPvar );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft , 'Robust', 'LAR');




